export const GET_INVITE_LIST = 'GET_INVITE_LIST'
export const GET_INVITE_DETAIL = 'GET_INVITE_DETAIL'
export const GET_INVITE_COMMENT = 'GET_INVITE_COMMENT'
export const POST_COMMENT = 'POST_COMMENT'
